### ISSUE TITLE
How should I go about implementing the "object" system?

### ISSUE THREAD

**Issue by Radfordhound** [Radfordhound/Project-Unique#5]
Hi all! First off, I'd like to apologize for my in-activity on this project. I've been rather "tied up" in other things and haven't had as much time to work on Project Unique/LGM.

Anyhoo, with that out of the way, let's get into the actual question. **How should I go about implementing the "object" system?**

Essentially, what I mean by that is how exactly do you think I should make "objects" with basic shared functions and variables that can be overridden, similar to the method engines such as Game Maker use? As in, what is the best method to do this in code?

In C# (A language I'm much more comfortable with.), I can make a class called "Object" which contains some basic variables/functions that all objects will share. Then I make virtual functions (Such as "Step.") which can be overridden in custom objects created by the user. Any code that needs to be ran before the override-able events can be done easily. (Such as with an "Update" function, which runs said code before calling the previously-mentioned virtual step function.)

This means users can make a new object that moves forward by one pixel every step simply by doing something like this:

```C#
using ProjectUnique;

namespace TestGame
{
    public class obj_test : Object
    {
        public override void Step()
        {
            x++;
        } 
    }
}
```

While really in the background there's something more like this going on (Using a couple LOVE2D functions for the purposes of the example, although this obviously can't be done in C# as of now.):

Object.cs:
```C#
namespace ProjectUnique
{
    public class Object
    {
        public int x = 0;
        public int y = 0;

        public void Update()
        {
            //TODO: Add code that needs to be completed before step event.
            this.Step();
        }

        public virtual void Step(){}
    }
}
```

Resources.cs:
```C#
namespace ProjectUnique
{
    public static class Resources
    {    
        public static List<ProjectUnique.Object> objects = new List<ProjectUnique.Object>();

        public class Objects
        {
            public void Add(Object obj)
            {
                Resources.objects.Add(obj);
            }
        }

        public void love.update(dt)
        {
            foreach (Object obj in objects)
            {
                obj.Update();
            }
        }
    }
}
```

Apologies if I didn't explain clearly. Basically, this system would allow developers using Project Unique to be able to add objects extremely easily (Adding the above-mentioned obj_test to the screen would literally be as simple as this: ```Resources.Objects.Add(new obj_test());```.), and it wouldn't be too hard to implement. (I basically just did it with the above examples.)

However, in Lua, this is much more difficult. From my understanding, there are no "virtual" functions in Lua (Without an extra library, of course.), making adding the ability to write custom code for your object (A complete necessity for the goals of this project!) very difficult. Also, while there is class support through the use of certain libraries (Like the already in-use "Project HUMP."), it's very... shall we say, "patchy", as it was only implemented to allow such a feature to exist in the first place (Really a must in today's world in my opinion. I mean, come on! Even C++ had object-orientation!) and not to be a complete, 100% advanced object-orientation library.

So, how should I go about doing this in Lua? Please let me know if you have any ideas! They're greatly appreciated! Also, if you have any questions as to something I poorly explained, please make a comment asking about it! I'll gladly answer any questions to my best extents. Thanks again for contributing to this project! :smile:

**Comment by Bobbyjoness** [comment]
Use hump.classes it allows mixins and all that.

**Comment by Bobbyjoness** [comment]
But I been working on a local copy to make a little something cool that might blow your socks off lol.  I'll make a pull request when its ready. It uses a ECS

**Comment by Radfordhound** [comment]
W-What? But I already looked at the HUMP class documentation and there was no way to... *reads documentation again and notices class.include which I somehow missed.*

Weeeellllpppp I feel stupid! :| Should I close this issue, then?
